SELECT 
    H.HISTORY_ID,
    FLOOR(H.DURATION * C.DAILY_FEE * (100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM (
    SELECT 
        HISTORY_ID,
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) H
JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
   AND (
        (H.DURATION >= 7 AND H.DURATION < 30 AND D.DURATION_TYPE = '7일 이상')
     OR (H.DURATION >= 30 AND H.DURATION < 90 AND D.DURATION_TYPE = '30일 이상')
     OR (H.DURATION >= 90 AND D.DURATION_TYPE = '90일 이상')
   )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;
